# Generated by Django 4.0.1 on 2022-01-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_username', models.CharField(default='raven88', max_length=40)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='hacker@trill.com', max_length=200)),
                ('created_at', models.DateField()),
                ('modified_at', models.DateTimeField()),
            ],
        ),
    ]
