# Generated by Django 4.0.1 on 2022-01-28 20:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_username', models.CharField(default='username_not_defined', max_length=40)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='you@you.com', max_length=200)),
                ('created_at', models.DateField()),
                ('modified_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(default='User', max_length=10)),
                ('created_at', models.DateField()),
                ('modified_at', models.DateTimeField()),
                ('login_password', models.CharField(default='¯J@\n,ëyc¤$ÙÏ7y\x17\\\x8d%\x8f¬ø£\x1eè¼\x19IÜ\x06\x0e\x10æ', max_length=100)),
                ('digital_base_personality', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=8)),
                ('digital_future_personality', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=8)),
                ('human_race', models.CharField(default='Libyan', max_length=100)),
                ('question_gender', models.BooleanField(default=False)),
                ('question_god', models.BooleanField(default=False)),
                ('question_society', models.BooleanField(default=False)),
                ('is_life_random', models.BooleanField(default=False)),
                ('one_humanity', models.BooleanField(default=False)),
                ('is_internet_a_happy_place', models.BooleanField(default=True)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser')),
            ],
        ),
        migrations.CreateModel(
            name='User_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(default='Credit / Debit Card', max_length=10)),
                ('payment_provider', models.CharField(default='STRIPE', max_length=10)),
                ('payment_status', models.BooleanField(default=False)),
                ('total_money_spent', models.FloatField(default=0.0)),
                ('created_at', models.DateField()),
                ('modified_at', models.DateTimeField()),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser')),
            ],
        ),
        migrations.CreateModel(
            name='User_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(max_length=100)),
                ('address_state', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=10)),
                ('planet', models.CharField(default='Earth', max_length=10)),
                ('cell_phone', models.CharField(default='0000', max_length=100000)),
                ('created_at', models.DateField()),
                ('modified_at', models.DateTimeField()),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser')),
            ],
        ),
    ]
