# Generated by Django 4.0.5 on 2022-08-19 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collectionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.productcollection'),
        ),
        migrations.AlterField(
            model_name='productcollection',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.metauser'),
        ),
    ]
