# Generated by Django 4.0.1 on 2022-06-30 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bodegaCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='John Doe', max_length=255)),
                ('email', models.CharField(default='johndoe@email.com', max_length=255)),
                ('customerID', models.CharField(max_length=500)),
                ('paymentMethodID', models.CharField(max_length=500)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoostTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=11)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='creatorSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriptionName', models.CharField(max_length=300)),
                ('subscriptionDescription', models.CharField(max_length=500)),
                ('amount', models.IntegerField(default=0)),
                ('currency', models.CharField(max_length=255)),
                ('chargingFrequency', models.CharField(max_length=300)),
                ('stripeProductID', models.CharField(max_length=400)),
                ('stripePriceID', models.CharField(max_length=400)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaUserTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metauserStatus', models.CharField(default='ACTIVE GUEST CREATOR', max_length=255)),
                ('trophiesAllocated', models.TextField(default='BABYSTEPS REVOLUTIONARY')),
                ('projectBodegaLogo', models.ImageField(default='https://bdgdaostorage.blob.core.windows.net/media/bodegaLogoBackend.jpeg', upload_to='')),
                ('metauserProfileLogo', models.ImageField(default='https://bdgdaostorage.blob.core.windows.net/media/bodegaLogoBackend.jpeg', upload_to='')),
                ('subscribersNumber', models.IntegerField(default=0)),
                ('followersNumber', models.IntegerField(default=0)),
                ('subscriptionActive', models.BooleanField(default=False)),
                ('accessLevelClearance', models.FloatField(default=3.5)),
                ('isProfilePrivate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MunchiesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('munchiesPageName', models.CharField(max_length=255)),
                ('munchiesCoverImage', models.FileField(upload_to='munchies/coverImage')),
                ('munchiesPageViews', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MunchiesVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('munchiesVideo', models.FileField(upload_to='munchies/videos')),
                ('munchiesCaption', models.CharField(max_length=200)),
                ('munchiesVideoTags', models.CharField(max_length=200)),
                ('munchiesDislikes', models.IntegerField(default=0)),
                ('munchiesVideoViews', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('munchiesPageID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.munchiespage')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('image', models.FileField(default='https://bdgdaostorage.blob.core.windows.net/media/product/product_image1/white-transparent-bdga.png', upload_to='notifications/image_metadata')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeChargeID', models.TextField(blank=True)),
                ('orderCompleted', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeChargeID', models.TextField(blank=True)),
                ('orderCompleted', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='stripeAccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0)),
                ('currency', models.TextField()),
                ('pendingAmount', models.FloatField(default=0.0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='stripeAccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeAccountID', models.CharField(max_length=400, unique=True)),
                ('businessType', models.CharField(default='Digital Services', max_length=300)),
                ('businessName', models.CharField(blank=True, max_length=255)),
                ('businessDescription', models.CharField(blank=True, max_length=255)),
                ('businessCity', models.CharField(blank=True, max_length=255)),
                ('businessCountry', models.CharField(blank=True, max_length=255)),
                ('businessLine1', models.CharField(blank=True, max_length=255)),
                ('businessLine2', models.CharField(blank=True, max_length=255)),
                ('businessPostalCode', models.CharField(blank=True, max_length=255)),
                ('businessEmail', models.CharField(blank=True, max_length=255)),
                ('businessBankName', models.CharField(blank=True, max_length=255)),
                ('businessPhone', models.CharField(blank=True, max_length=255)),
                ('businessURL', models.CharField(blank=True, max_length=255)),
                ('businessLogo', models.ImageField(blank=True, upload_to='')),
                ('accountPaymentStatus', models.CharField(blank=True, max_length=255)),
                ('accountTransfersStatus', models.CharField(blank=True, max_length=255)),
                ('accountCurrency', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='stripeAccountTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.CharField(max_length=500)),
                ('payoutAmount', models.FloatField(default=0.0)),
                ('payoutOrderInfo', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('stripeAccountInfoID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.stripeaccountinfo')),
            ],
        ),
        migrations.CreateModel(
            name='stripeCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeChargeID', models.CharField(max_length=300)),
                ('stripeCustomerID', models.CharField(max_length=400)),
                ('stripePaymentMethodID', models.CharField(blank=True, default='None', max_length=400)),
                ('amount', models.FloatField(default=0.0)),
                ('currency', models.TextField(default='us')),
                ('description', models.CharField(max_length=400)),
                ('capturedStatus', models.BooleanField(default=False)),
                ('paymentStatus', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('bodegaCustomerID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.bodegacustomer')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerID', models.CharField(max_length=400)),
                ('priceID', models.CharField(max_length=400)),
                ('subscriptionID', models.CharField(max_length=400)),
                ('productID', models.CharField(max_length=400)),
                ('amount', models.IntegerField(default=0)),
                ('invoiceID', models.CharField(max_length=400)),
                ('status', models.CharField(max_length=400)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Particpant',
            new_name='Participant',
        ),
        migrations.RenameField(
            model_name='chatroom',
            old_name='is_room_active',
            new_name='isRoomPrivate',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_product_digital',
            new_name='privateProduct',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='hashkey',
            new_name='productHashkey',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='sellingPrice',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productMetaDataID',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_themesID',
        ),
        migrations.RemoveField(
            model_name='productmetadata',
            name='assistance_ask',
        ),
        migrations.RemoveField(
            model_name='productmetadata',
            name='encrypt_product',
        ),
        migrations.RemoveField(
            model_name='productmetadata',
            name='hours_invested',
        ),
        migrations.RemoveField(
            model_name='productmetadata',
            name='is_product_digital',
        ),
        migrations.RemoveField(
            model_name='productmetadata',
            name='nsfw_content',
        ),
        migrations.RemoveField(
            model_name='productmetadata',
            name='product_image2',
        ),
        migrations.RemoveField(
            model_name='productmetadata',
            name='product_image3',
        ),
        migrations.RemoveField(
            model_name='productmetadata',
            name='product_image4',
        ),
        migrations.RemoveField(
            model_name='productmetadata',
            name='production_cost',
        ),
        migrations.RemoveField(
            model_name='productmetadata',
            name='production_time_days',
        ),
        migrations.RemoveField(
            model_name='productmetadata',
            name='size_chart',
        ),
        migrations.RemoveField(
            model_name='productmetadata',
            name='unit_sold_expectation',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='payment_provider',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='tags',
            field=models.TextField(default='#ROOM'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='metauserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='backend.metauser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='producDescription',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='productName',
            field=models.TextField(default=None, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_image2',
            field=models.FileField(default='https://bdgdaostorage.blob.core.windows.net/media/product/product_image1/white-transparent-bdga.png', upload_to='product/product_image2'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image3',
            field=models.FileField(default='https://bdgdaostorage.blob.core.windows.net/media/product/product_image1/white-transparent-bdga.png', upload_to='product/product_image3'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image4',
            field=models.FileField(default='https://bdgdaostorage.blob.core.windows.net/media/product/product_image1/white-transparent-bdga.png', upload_to='product/product_image4'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_chart',
            field=models.FileField(default='https://bdgdaostorage.blob.core.windows.net/media/product/product_image1/white-transparent-bdga.png', upload_to='product/size_chart'),
        ),
        migrations.AddField(
            model_name='product',
            name='subscriptionProduct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmetadata',
            name='productID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='backend.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpayment',
            name='stripeAccountID',
            field=models.TextField(default='Project-Bodega Member Stripe Account ID'),
        ),
        migrations.AlterField(
            model_name='blascore',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blascore',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bodegacognitiveinventory',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bodegacognitiveinventory',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bodegacognitiveitem',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bodegacognitiveitem',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bodegacognitiveperson',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bodegacognitiveperson',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bodegadept',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bodegadept',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bodegaface',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bodegaface',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bodegapersonalizer',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bodegapersonalizer',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bodegavision',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bodegavision',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='modified_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='bid_type',
            field=models.TextField(choices=[('FIXED-PAYMENT', 'FIXED-PAYMENT'), ('COMMISSION-%-ON-SALES', 'COMMISSION-%-ON-SALES'), ('FREE-HELP-FROM-THE-COMMUNITY', 'FREE-HELP-FROM-THE-COMMUNITY')]),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='creator_collab_choice',
            field=models.TextField(choices=[('FIXED-PAYMENT', 'FIXED-PAYMENT'), ('COMMISSION-%-ON-SALES', 'COMMISSION-%-ON-SALES'), ('FREE-HELP-FROM-THE-COMMUNITY', 'FREE-HELP-FROM-THE-COMMUNITY')]),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='payment_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.userpayment'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.orderdetail'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image1',
            field=models.FileField(default='https://bdgdaostorage.blob.core.windows.net/media/product/product_image1/white-transparent-bdga.png', upload_to='product/product_image1'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productmetadata',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productmetadata',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sentinoinventory',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sentinoinventory',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sentinoitemclassification',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sentinoitemclassification',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sentinoitemprojection',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sentinoitemprojection',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sentinoitemproximity',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sentinoitemproximity',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sentinoprofile',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sentinoprofile',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sentinoselfdescription',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sentinoselfdescription',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='modified_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shoppingsession',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shoppingsession',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='modified_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='solomonv0',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='solomonv0',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sysopsagent',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sysopsagent',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sysopsagentrepo',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sysopsagentrepo',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sysopsdemandnode',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sysopsdemandnode',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sysopsproject',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sysopsproject',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sysopssupplynode',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sysopssupplynode',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='ProductThemes',
        ),
        migrations.AddField(
            model_name='subscribers',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.metauser'),
        ),
        migrations.AddField(
            model_name='stripeaccountinfo',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.metauser'),
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product'),
        ),
        migrations.AddField(
            model_name='ordersuccess',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.metauser'),
        ),
        migrations.AddField(
            model_name='ordersuccess',
            name='order_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.orderdetail'),
        ),
        migrations.AddField(
            model_name='orderfailure',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.metauser'),
        ),
        migrations.AddField(
            model_name='orderfailure',
            name='order_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.orderdetail'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.metauser'),
        ),
        migrations.AddField(
            model_name='metausertags',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.metauser'),
        ),
        migrations.AddField(
            model_name='creatorsubscription',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.metauser'),
        ),
        migrations.AddField(
            model_name='boosttags',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.metauser'),
        ),
        migrations.AddField(
            model_name='bodegacustomer',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.metauser'),
        ),
        migrations.AddField(
            model_name='product',
            name='boostTagsID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.boosttags'),
            preserve_default=False,
        ),
    ]
