# Generated by Django 4.0.1 on 2022-03-24 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOwnershipLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metauserLedger', models.JSONField(blank=True, null=True)),
                ('bidPriceHistory', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateField()),
                ('modified_at', models.DateTimeField()),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.product')),
            ],
        ),
    ]
