# Generated by Django 4.0.5 on 2022-08-24 16:50

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productInventoryID',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productVariants',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderledger',
            name='customTrackingLabel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderledger',
            name='generateTrackingLabel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='productID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.product'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='created_by',
            field=models.ForeignKey(default=backend.models.get_sentinel_MetaUser_id, on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
    ]
