# Generated by Django 4.0.1 on 2022-06-30 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_bodegacustomer_boosttags_creatorsubscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='John Doe', max_length=255)),
                ('email', models.CharField(default='johndoe@email.com', max_length=255)),
                ('customerID', models.CharField(max_length=500)),
                ('paymentMethodID', models.CharField(max_length=500)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('metauserID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.metauser')),
            ],
        ),
        migrations.AlterField(
            model_name='stripecharges',
            name='bodegaCustomerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.customerpayment'),
        ),
    ]
