# Generated by Django 4.0.1 on 2022-05-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_shoppingcartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmetadata',
            name='size_chart',
            field=models.FileField(default='https://bdgdaostorage.blob.core.windows.net/media/product/product_image1/ascii-art-2560x1440.png', upload_to='product/size_chart'),
        ),
    ]
