# Generated by Django 4.0.5 on 2022-08-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_product_discounted_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderledger',
            name='customerReceived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderledger',
            name='merchantDelivered',
            field=models.BooleanField(default=False),
        ),
    ]
