# Generated by Django 4.0.1 on 2022-02-12 22:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_social_bodegacoins_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='numberofclicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='numberofcomments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='numberofdislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='numberoflikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='totaltimespentonproduct_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='userID_array_of_comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=None, size=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='userID_array_of_dislikes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=None, size=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='userID_array_of_likes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=None, size=100),
            preserve_default=False,
        ),
    ]
