# Generated by Django 4.0.1 on 2022-01-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_chat_room_collaboration_discount_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='hashkey',
            field=models.TextField(default='a805a157fa3a7235b206a80feb51122b867afa8e5cdf0278ccb259588f5d5dc8', unique=True),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='hashkey',
            field=models.TextField(default='58c59fac79617816106f5c2554a1c7737f1af150382d4b777dc89c85e38bcf5dba2b6bf1a8ee3295e8141354eaecd5ffff60b70f8e9f8ef3f24cc4fb488603c8', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hashkey',
            field=models.TextField(default='1c0a8cc402c20af464852890122fff8b04881195', unique=True),
        ),
    ]
