# Generated by Django 4.0.5 on 2022-11-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_productcategory_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodegaannouncementbanner',
            name='covermedia1',
            field=models.FileField(default='8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='BodegaAnnouncementBanner/covermedia1'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_name',
            field=models.TextField(),
        ),
    ]
