# Generated by Django 4.0.5 on 2022-07-05 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_notifications_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isPhysicalProduct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image1',
            field=models.FileField(default='https://projectbodegadb.blob.core.windows.net/media/8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='product/product_image1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image2',
            field=models.FileField(default='https://projectbodegadb.blob.core.windows.net/media/8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='product/product_image2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image3',
            field=models.FileField(default='https://projectbodegadb.blob.core.windows.net/media/8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='product/product_image3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image4',
            field=models.FileField(default='https://projectbodegadb.blob.core.windows.net/media/8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='product/product_image4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_chart',
            field=models.FileField(default='https://projectbodegadb.blob.core.windows.net/media/8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='product/size_chart'),
        ),
        migrations.CreateModel(
            name='yerrrCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaignName', models.CharField(default='Your Campaign Name', max_length=255)),
                ('campaignDescription', models.CharField(default='Why you want to collaborate on this product?', max_length=600)),
                ('media1', models.FileField(default='https://projectbodegadb.blob.core.windows.net/media/8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='yerrr/media1')),
                ('caption1', models.CharField(default='Caption for Media 1', max_length=255)),
                ('media2', models.FileField(default='https://projectbodegadb.blob.core.windows.net/media/8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='yerrr/media2')),
                ('caption2', models.CharField(default='Caption for Media 2', max_length=255)),
                ('media3', models.FileField(default='https://projectbodegadb.blob.core.windows.net/media/8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='yerrr/media3')),
                ('caption3', models.CharField(default='Caption for Media 3', max_length=255)),
                ('collaborationType', models.TextField(choices=[('FIXED-ONE-TIME-PAYMENT', 'FIXED-ONE-TIME-PAYMENT'), ('COMMISSION-%-ON-SALES', 'COMMISSION-%-ON-SALES'), ('FREE-HELP-FROM-THE-COMMUNITY', 'FREE-HELP-FROM-THE-COMMUNITY')])),
                ('campaignRules', models.CharField(default='Product Owner can list rules for the campaign.', max_length=255)),
                ('collaboratorFixedPaymentAmount', models.IntegerField(default=0)),
                ('collaboratorCommissionPercentageAmount', models.IntegerField(default=0)),
                ('yerrrStatus', models.BooleanField(default=False)),
                ('ownerAcceptBid', models.BooleanField(default=False)),
                ('collaboratorAcceptBid', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('collaboratorMetaUserID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.metauser')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.product')),
            ],
        ),
    ]
