# Generated by Django 4.0.1 on 2022-02-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_product_price_product_numberofclicks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
        model_name='user_type',
        name='describe_yourself',
        ),
        migrations.AddField(
            model_name='user_type',
            name='describe_yourself',
            field=models.JSONField(blank=True, null=True),
        ),

        migrations.RemoveField(
        model_name='user_type',
        name='digital_base_personality',
        ),
        migrations.AddField(
            model_name='user_type',
            name='digital_base_personality',
            field=models.JSONField(blank=True, null=True),
        ),

        migrations.RemoveField(
            model_name='user_type',
            name='digital_future_personality',
        ),
        migrations.AddField(
            model_name='user_type',
            name='digital_future_personality',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
