# Generated by Django 4.0.1 on 2022-01-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_message_hashkey_alter_metauser_hashkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='hashkey',
            field=models.TextField(default='12ea96ea0be2ea19c93bade073607e9504c516415d47b8fd6d5ffa88cef6d15f', unique=True),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='hashkey',
            field=models.TextField(default='5572332f6e997e682f2d0606ce8279bd694d91d3b0f9660fdf4c2162beff6754377c4fe620b509d11d7a1f744878aeab8e7e85a187b296039fd72d084778a270', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hashkey',
            field=models.TextField(default='f066b20611c8f0b189a645a0195fbb01610c15dc', unique=True),
        ),
    ]
