# Generated by Django 4.0.5 on 2022-09-01 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_orderledger_customerreceived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorsubscription',
            name='shopID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.shop'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='country',
            field=models.TextField(max_length=2),
        ),
    ]
