# Generated by Django 4.0.1 on 2022-02-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_message_hashkey_alter_metauser_hashkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='hashkey',
            field=models.TextField(default='28066afd2e929426fa132f122ed023337dfc83d5eb798771d072a2792f14851d', unique=True),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='hashkey',
            field=models.TextField(default='68a7c0c12855d5f0a5ccb171d5058aa69c0eaf54fd57a7f4708f4eac1fda7f03c8c2bcc79f6d49f66acafc929f1542bded343c5cbb300c3b8df51aca22f91b79', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hashkey',
            field=models.TextField(default='21cef62faf121d2a4054042972301dbb6df52a5c', unique=True),
        ),
    ]
