# Generated by Django 4.0.5 on 2022-07-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_product_isphysicalproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.TextField(max_length=140, unique=True),
        ),
    ]
