# Generated by Django 4.0.5 on 2022-09-01 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_creatorsubscription_shopid_alter_shop_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='shopID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.shop'),
        ),
        migrations.AlterField(
            model_name='bodegaserver',
            name='isRoomPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
