# Generated by Django 4.0.1 on 2022-05-28 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_userpayment_payment_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunchiesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('munchiesPageName', models.CharField(max_length=255)),
                ('munchiesCoverImage', models.FileField(upload_to='munchies/coverImage')),
                ('munchiesPageViews', models.IntegerField(default=0)),
                ('created_at', models.DateField()),
                ('modified_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MunchiesVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('munchiesVideo', models.FileField(upload_to='munchies/videos')),
                ('munchiesCaption', models.CharField(max_length=200)),
                ('munchiesVideoTags', models.CharField(max_length=200)),
                ('munchiesDislikes', models.IntegerField(default=0)),
                ('munchiesVideoViews', models.IntegerField(default=0)),
                ('created_at', models.DateField()),
                ('modified_at', models.DateTimeField()),
                ('munchiesPageID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.munchiespage')),
            ],
        ),
    ]
