# Generated by Django 4.0.1 on 2022-02-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_user_type_describe_yourself_and_more'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='product_themes',
            name='audience_traits',
        ),
        migrations.AddField(
            model_name='product_themes',
            name='audience_traits',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
