# Generated by Django 4.0.5 on 2022-07-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_product_productname'),
    ]

    operations = [
        migrations.AddField(
            model_name='yerrrcollaboration',
            name='ownerMetaUserID',
            field=models.IntegerField(default=0),
        ),
    ]
