# Generated by Django 4.0.1 on 2022-02-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_product_themes_audience_traits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='blocked_list',
        ),
        migrations.AddField(
            model_name='social',
            name='blocked_list',
            field=models.JSONField(blank=True, null=True),
        ),

        migrations.RemoveField(
            model_name='social',
            name='comments',
        ),
        migrations.AddField(
            model_name='social',
            name='comments',
            field=models.JSONField(blank=True, null=True),
        ),

        migrations.RemoveField(
            model_name='social',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='social',
            name='dislikes',
            field=models.JSONField(blank=True, null=True),
        ),

        migrations.RemoveField(
            model_name='social',
            name='followers',
        ),
        migrations.AddField(
            model_name='social',
            name='followers',
            field=models.JSONField(blank=True, null=True),
        ),

        migrations.RemoveField(
            model_name='social',
            name='following',
        ),
        migrations.AddField(
            model_name='social',
            name='following',
            field=models.JSONField(blank=True, null=True),
        ),

        migrations.RemoveField(
            model_name='social',
            name='likes',
        ),
        migrations.AddField(
            model_name='social',
            name='likes',
            field=models.JSONField(blank=True, null=True),
        ),

        migrations.RemoveField(
            model_name='social',
            name='products_clickedOn',
        ),
        migrations.AddField(
            model_name='social',
            name='products_clickedOn',
            field=models.JSONField(blank=True, null=True),
        ),

        migrations.RemoveField(
            model_name='social',
            name='saved_content',
        ),
        migrations.AddField(
            model_name='social',
            name='saved_content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
