# Generated by Django 4.0.1 on 2022-02-02 03:28

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_message_hashkey_alter_metauser_hashkey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_size_matrix', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=15), size=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='metauser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='metauser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_multiple_variants',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='user_type',
            name='human_race',
        ),
        migrations.RemoveField(
            model_name='user_type',
            name='is_internet_a_happy_place',
        ),
        migrations.RemoveField(
            model_name='user_type',
            name='is_life_random',
        ),
        migrations.RemoveField(
            model_name='user_type',
            name='login_password',
        ),
        migrations.RemoveField(
            model_name='user_type',
            name='one_humanity',
        ),
        migrations.RemoveField(
            model_name='user_type',
            name='question_gender',
        ),
        migrations.RemoveField(
            model_name='user_type',
            name='question_god',
        ),
        migrations.RemoveField(
            model_name='user_type',
            name='question_society',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_type',
            name='about_you_belief',
            field=models.TextField(choices=[('1', 'I believe that people or organizations cant be trusted with anything'), ('2', 'I believe that nowadays, free will is fucking hard.'), ('3', 'I believe that anonymity gives me power to create wihout fear of failure.'), ('4', 'I believe that we all are special in some way - Genetic mutations'), ('5', 'I believe that our society is all about conformism & accumulation of material-shit'), ('6', 'I believe that I do not mildy resonate with any subjective statements above.')], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_type',
            name='about_you_belief2',
            field=models.TextField(choices=[('1', 'I believe that people or organizations cant be trusted with anything'), ('2', 'I believe that nowadays, free will is fucking hard.'), ('3', 'I believe that anonymity gives me power to create wihout fear of failure.'), ('4', 'I believe that we all are special in some way - Genetic mutations'), ('5', 'I believe that our society is all about conformism & accumulation of material-shit'), ('6', 'I believe that I do not mildy resonate with any subjective statements above.')], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_type',
            name='about_you_disbelief',
            field=models.TextField(choices=[('1', 'I dont belief in the concept of banks, goverments, race, color, religion because these myths stop us from questioning who we truly are'), ('2', 'I dont belief that any government cares about the Libyan slavery crisis'), ('3', 'I dont belief in Mars colonization, I think we should all work to fix mother earth.'), ('4', 'I dont belief in the concept of monogamous relationships'), ('5', 'I dont belief that people understand others perspectives.'), ('6', 'I dont belief in anything.')], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_type',
            name='chest_size',
            field=models.TextField(default='[XL, 30Inch]'),
        ),
        migrations.AddField(
            model_name='user_type',
            name='describe_yourself',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=None, size=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_type',
            name='shoe_size',
            field=models.FloatField(default=11.5),
        ),
        migrations.AddField(
            model_name='user_type',
            name='waist_size',
            field=models.TextField(default='[XL, 36]'),
        ),
        migrations.AddField(
            model_name='user_type',
            name='why_did_you_join_bodega',
            field=models.TextField(choices=[('Anonymity', 'Anonymity'), ('Creative-Freedom', 'Creative-Freedom'), ('Create-Digital-Art', 'Create-Digital-Art'), ('Connect-With-Global-Audience', 'Connect-With-Global-Audience'), ('All-of-the-above', 'All-of-the-above'), ('Just-Browsing', 'Just-Browsing')], default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='hashkey',
            field=models.TextField(default='0b4078d48b8ba5a3d24ee1c7df902e481d7d886f6707912a2158cf6452532dc2', unique=True),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='email',
            field=models.EmailField(default='whoeveryouwannabe@human.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='hashkey',
            field=models.TextField(default='482ab891697f2516d5a1e27ebd4067a446ab1fd8e6c64d261ae5c711ec3d8e8e971886a1b9c7b62591dc34e9bee96bbc6948acc0303da9f87417467c5f7f9fea', unique=True),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='password',
            field=models.TextField(default='Go for easy 4-digit numeric code - which IS NOT avail on the internet', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='clicks_on_product',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='hashkey',
            field=models.TextField(default='28e3062baae07bfdf5f0f25f6d8e7a9f18ec4db6', unique=True),
        ),
        migrations.AlterField(
            model_name='user_payment',
            name='payment_type',
            field=models.TextField(choices=[('DEBIT/CREDIT-CARD', 'DEBIT/CREDIT-CARD'), ('PAYPAL', 'PAYPAL'), ('CRYPTO(BETA)', 'CRYPTO(BETA)')]),
        ),
        migrations.AddField(
            model_name='product',
            name='price_sizeID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.product_variants'),
            preserve_default=False,
        ),
    ]
