# Generated by Django 4.0.1 on 2022-02-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_social_blocked_list_alter_social_comments_and_more'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='shop',
            name='all_products',
        ),
        migrations.AddField(
            model_name='shop',
            name='all_products',
            field=models.JSONField(blank=True, null=True),
        ),

        migrations.RemoveField(
            model_name='shop',
            name='all_user_data',
        ),
        migrations.AddField(
            model_name='shop',
            name='all_user_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='shop',
            name='assistance_ask',
        ),
        migrations.AddField(
            model_name='shop',
            name='assistance_ask',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shop_traits',
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_traits',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
