# Generated by Django 4.0.5 on 2022-09-21 20:21

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_metauseraccountstatus_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memoriesMedia', models.FileField(default='8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='bodegaMerchant/memories/media')),
                ('memoriesCaption', models.TextField(blank=True)),
                ('expirationCondition', models.TextField(choices=[('5MINS', '5MINS'), ('30MINS', '30MINS'), ('24HOURS', '24HOURS'), ('NEVER', 'NEVER')])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('ownerMetaUserID', models.ForeignKey(default=backend.models.get_sentinel_MetaUser_id, on_delete=models.SET(backend.models.get_sentinel_MetaUser), to='backend.metauser')),
            ],
        ),
        migrations.CreateModel(
            name='BodegaSubscriberLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerID', models.TextField()),
                ('stripePriceID', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('metauserID', models.ForeignKey(default=backend.models.get_sentinel_MetaUser_id, on_delete=models.SET(backend.models.get_sentinel_MetaUser), to='backend.metauser')),
            ],
        ),
        migrations.CreateModel(
            name='BodegaPublicURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metausername', models.TextField(blank=True)),
                ('bioCaption', models.TextField(blank=True)),
                ('subscriptionButton', models.BooleanField(default=False)),
                ('yerrrButton', models.BooleanField(default=False)),
                ('backgroundImage', models.FileField(default='8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='bodegaMerchant/bodegaPublicURL/contentPage/backgroundImage')),
                ('backgroundColor', models.TextField(default='TRANSPARENT')),
                ('profileImage', models.FileField(blank=True, upload_to='bodegaMerchant/bodegaPublicURL/profileImage/media')),
                ('coverMedia', models.FileField(default='8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='bodegaMerchant/bodegaPublicURL/contentPage/media1')),
                ('media1', models.FileField(default='8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='bodegaMerchant/bodegaPublicURL/contentPage/media1')),
                ('media2', models.FileField(default='8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='bodegaMerchant/bodegaPublicURL/contentPage/media2')),
                ('media3', models.FileField(default='8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='bodegaMerchant/bodegaPublicURL/contentPage/media3')),
                ('media4', models.FileField(default='8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='bodegaMerchant/bodegaPublicURL/contentPage/media4')),
                ('media5', models.FileField(default='8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='bodegaMerchant/bodegaPublicURL/contentPage/media5')),
                ('media6', models.FileField(default='8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='bodegaMerchant/bodegaPublicURL/contentPage/media6')),
                ('media7', models.FileField(default='8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='bodegaMerchant/bodegaPublicURL/contentPage/media1')),
                ('media8', models.FileField(default='8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='bodegaMerchant/bodegaPublicURL/contentPage/media2')),
                ('media9', models.FileField(default='8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='bodegaMerchant/bodegaPublicURL/contentPage/media3')),
                ('media10', models.FileField(default='8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='bodegaMerchant/bodegaPublicURL/contentPage/media4')),
                ('media11', models.FileField(default='8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='bodegaMerchant/bodegaPublicURL/contentPage/media5')),
                ('media12', models.FileField(default='8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='bodegaMerchant/bodegaPublicURL/contentPage/media6')),
                ('media13', models.FileField(default='8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='bodegaMerchant/bodegaPublicURL/contentPage/media6')),
                ('media14', models.FileField(default='8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='bodegaMerchant/bodegaPublicURL/contentPage/media6')),
                ('media15', models.FileField(default='8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='bodegaMerchant/bodegaPublicURL/contentPage/media6')),
                ('caption1', models.URLField(blank=True)),
                ('caption2', models.URLField(blank=True)),
                ('caption3', models.URLField(blank=True)),
                ('caption4', models.URLField(blank=True)),
                ('caption5', models.URLField(blank=True)),
                ('caption6', models.URLField(blank=True)),
                ('caption7', models.URLField(blank=True)),
                ('caption8', models.URLField(blank=True)),
                ('caption9', models.URLField(blank=True)),
                ('caption10', models.URLField(blank=True)),
                ('caption11', models.URLField(blank=True)),
                ('caption12', models.URLField(blank=True)),
                ('caption13', models.URLField(blank=True)),
                ('caption14', models.URLField(blank=True)),
                ('caption15', models.URLField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('ownerMetaUserID', models.ForeignKey(default=backend.models.get_sentinel_MetaUser_id, on_delete=models.SET(backend.models.get_sentinel_MetaUser), to='backend.metauser')),
            ],
        ),
        migrations.CreateModel(
            name='BodegaCreditCardLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('currency', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('customerID', models.TextField()),
                ('paymentMethodID', models.TextField()),
                ('bodegaCustomerID', models.IntegerField()),
                ('stripeAccountInfoID', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('metauserID', models.ForeignKey(default=backend.models.get_sentinel_MetaUser_id, on_delete=models.SET(backend.models.get_sentinel_MetaUser), to='backend.metauser')),
            ],
        ),
    ]
