# Generated by Django 4.0.1 on 2022-06-07 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_boosttags_alter_product_product_themesid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_themesID',
            new_name='boostTagsID',
        ),
    ]
