# Generated by Django 4.0.1 on 2022-02-15 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_shop_all_products_alter_shop_all_user_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_by',
            new_name='user_ID',
        ),
    ]
