# Generated by Django 4.0.1 on 2022-06-07 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_product_themesid_product_boosttagsid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_product_digital',
            new_name='privateProduct',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='hashkey',
            new_name='productHashkey',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='sellingPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productMetaDataID',
        ),
        migrations.RemoveField(
            model_name='productmetadata',
            name='assistance_ask',
        ),
        migrations.RemoveField(
            model_name='productmetadata',
            name='encrypt_product',
        ),
        migrations.RemoveField(
            model_name='productmetadata',
            name='hours_invested',
        ),
        migrations.RemoveField(
            model_name='productmetadata',
            name='is_product_digital',
        ),
        migrations.RemoveField(
            model_name='productmetadata',
            name='nsfw_content',
        ),
        migrations.RemoveField(
            model_name='productmetadata',
            name='product_image2',
        ),
        migrations.RemoveField(
            model_name='productmetadata',
            name='product_image3',
        ),
        migrations.RemoveField(
            model_name='productmetadata',
            name='product_image4',
        ),
        migrations.RemoveField(
            model_name='productmetadata',
            name='production_cost',
        ),
        migrations.RemoveField(
            model_name='productmetadata',
            name='production_time_days',
        ),
        migrations.RemoveField(
            model_name='productmetadata',
            name='size_chart',
        ),
        migrations.RemoveField(
            model_name='productmetadata',
            name='unit_sold_expectation',
        ),
        migrations.AddField(
            model_name='product',
            name='producDescription',
            field=models.CharField(default='Description', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='productName',
            field=models.TextField(default='productName', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_image2',
            field=models.FileField(default='https://bdgdaostorage.blob.core.windows.net/media/product/product_image1/white-transparent-bdga.png', upload_to='product/product_image2'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image3',
            field=models.FileField(default='https://bdgdaostorage.blob.core.windows.net/media/product/product_image1/white-transparent-bdga.png', upload_to='product/product_image3'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image4',
            field=models.FileField(default='https://bdgdaostorage.blob.core.windows.net/media/product/product_image1/white-transparent-bdga.png', upload_to='product/product_image4'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_chart',
            field=models.FileField(default='https://bdgdaostorage.blob.core.windows.net/media/product/product_image1/white-transparent-bdga.png', upload_to='product/size_chart'),
        ),
        migrations.AddField(
            model_name='product',
            name='subscriptionProduct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmetadata',
            name='productID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='backend.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productmetadata',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productmetadata',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
