# Generated by Django 4.0.5 on 2022-07-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_bodegasocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metausertags',
            name='coverBio1',
            field=models.TextField(default='Hello, My name is Dolores Abernathy', max_length=80),
        ),
        migrations.AddField(
            model_name='metausertags',
            name='coverBio2',
            field=models.TextField(default='Fashion Designer | NYU Grad', max_length=40),
        ),
        migrations.AddField(
            model_name='metausertags',
            name='coverBodegaImage',
            field=models.ImageField(default='https://projectbodegadb.blob.core.windows.net/media/coverImage.gif', upload_to=''),
        ),
    ]
