# Generated by Django 4.0.5 on 2022-10-04 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_bodegaannouncementbanner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productInventoryID',
        ),
        migrations.AddField(
            model_name='orderledger',
            name='productVariant',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderledger',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='productID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.product'),
        ),
        migrations.CreateModel(
            name='BodegaFollowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followerMetaUserID', models.IntegerField(blank=True)),
                ('followerMetaUserName', models.TextField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('ownerMetaUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser')),
            ],
        ),
    ]
