# Generated by Django 4.0.1 on 2022-02-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_created_by_product_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customer_unique_traits',
        ),
        migrations.AddField(
            model_name='product',
            name='customer_unique_traits',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_unique_traits',
        ),
        migrations.AddField(
            model_name='product',
            name='product_unique_traits',
            field=models.JSONField(blank=True, null=True),
        ),

        migrations.RemoveField(
            model_name='product',
            name='userID_array_of_comments',
        ),
        migrations.AddField(
            model_name='product',
            name='userID_array_of_comments',
            field=models.JSONField(blank=True, null=True),
        ),
         migrations.RemoveField(
            model_name='product',
            name='userID_array_of_dislikes',
        ),
        migrations.AddField(
            model_name='product',
            name='userID_array_of_dislikes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='userID_array_of_likes',
        ),
        migrations.AddField(
            model_name='product',
            name='userID_array_of_likes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
