# Generated by Django 4.0.1 on 2022-02-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_message_hashkey_alter_metauser_hashkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='hashkey',
            field=models.TextField(default='b84bbfb51a2d1c988491177cd8ac0c840e453233053b2621b435e6fa60a945d4', unique=True),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='hashkey',
            field=models.TextField(default='a5e1dfe435ee02945bb8372ae94650adca9e6bd57a4c3e2b66a91127f5cbf06855e9cb7f8ae2161331138ca2746d8863e0a686b9766aa45b1b68eb1f8d72e0f2', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hashkey',
            field=models.TextField(default='8ddb8fd8831ce74af791a0a601bf9ab6ca38d387', unique=True),
        ),
    ]
