# Generated by Django 4.0.5 on 2022-10-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_product_productinventoryid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metausertags',
            name='accessLevelClearance',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='metausertags',
            name='metauserStatus',
            field=models.CharField(default='ACTIVE BODEGA1k', max_length=255),
        ),
    ]
