# Generated by Django 4.0.1 on 2022-02-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_message_hashkey_alter_metauser_hashkey_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='profileprivate',
            new_name='makeprofileprivate',
        ),
        migrations.AlterField(
            model_name='message',
            name='hashkey',
            field=models.TextField(default='b3d40611d678cbba0979370dd5bbfd9401867a547924eba67e3d770d70a4c936', unique=True),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='hashkey',
            field=models.TextField(default='b7d03f9b32f1250f886cd2d5eb22d539aa1933b8ad47e69f52b4b60255f576761d9525d81c6007211c7706716bce4c0d570f09e40f6424f56add179f1c8263f7', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hashkey',
            field=models.TextField(default='49477c3ca98b057389fcaf6d745b82d5364bc2d4', unique=True),
        ),
    ]
