# Generated by Django 4.0.1 on 2022-06-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_particpant_participant_orderitem_metauserid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
