# Generated by Django 4.0.5 on 2022-07-12 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_yerrrcollaboration_campaigncoverimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderStatus', models.TextField(choices=[('PENDING', 'PENDING'), ('CANCELLED', 'CANCELLED'), ('FULFILLED', 'FULFILLED'), ('REFUNDED', 'REFUNDED')])),
                ('paymentCaptured', models.BooleanField(default=False)),
                ('orderAmount', models.FloatField(default=0.0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('customerMetauserID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.metauser')),
                ('merchantStripeAccountInfoID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.stripeaccountinfo')),
                ('orderDetailID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.orderdetail')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.product')),
                ('userAddress', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.useraddress')),
            ],
        ),
    ]
