# Generated by Django 4.0.1 on 2022-06-15 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_chatroom_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='stripeAccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeAccountID', models.CharField(max_length=400, unique=True)),
                ('businessType', models.CharField(default='Digital Services', max_length=300)),
                ('businessName', models.CharField(blank=True, max_length=255)),
                ('businessDescription', models.CharField(blank=True, max_length=255)),
                ('businessCity', models.CharField(blank=True, max_length=255)),
                ('businessCountry', models.CharField(blank=True, max_length=255)),
                ('businessLine1', models.CharField(blank=True, max_length=255)),
                ('businessLine2', models.CharField(blank=True, max_length=255)),
                ('businessPostalCode', models.CharField(blank=True, max_length=255)),
                ('businessEmail', models.CharField(blank=True, max_length=255)),
                ('businessBankName', models.CharField(blank=True, max_length=255)),
                ('businessPhone', models.CharField(blank=True, max_length=255)),
                ('businessURL', models.CharField(blank=True, max_length=255)),
                ('businessLogo', models.ImageField(blank=True, upload_to='')),
                ('accountPaymentStatus', models.CharField(blank=True, max_length=255)),
                ('accountTransfersStatus', models.CharField(blank=True, max_length=255)),
                ('accountCurrency', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('metauserID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.metauser')),
            ],
        ),
    ]
