# Generated by Django 4.0.5 on 2022-10-12 01:17

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_metausertags_accesslevelclearance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='producDescription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shopID',
            field=models.ForeignKey(default=backend.models.get_sentinel_Shop_id, on_delete=models.SET(backend.models.get_sentinel_Shop), to='backend.shop'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_name',
            field=models.TextField(choices=[('SHIRTS', 'SHIRTS'), ('BOTTOMS', 'BOTTOMS'), ('SNEAKERS', 'SNEAKERS'), ('THERMALS', 'THERMALS'), ('SHORTS', 'SHORTS'), ('HOME-DECOR', 'HOME-DECOR'), ('DIGITAL-ART', 'DIGITAL-ART'), ('MUSIC-FILE', 'MUSIC-FILE'), ('COLLECTIBLES', 'COLLECTIBLES'), ('DIGITAL-COLLECTIBLES', 'DIGITAL-COLLECTIBLES'), ('PHYSICAL-ACCESSORIES', 'PHYSICAL-ACCESSORIES'), ('ENTERTAINMENT', 'ENTERTAINMENT'), ('CREATORS', 'CREATORS')]),
        ),
    ]
