# Generated by Django 4.0.1 on 2022-02-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_profileprivate_social_makeprofileprivate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='hashkey',
            field=models.TextField(default='cbbf3c1d63a4178ace4a827650c5455c2b562102c83233c89779bb4d34d5b25e', unique=True),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='hashkey',
            field=models.TextField(default='3ea43d278971e48a1425ec4b25375b3e19e151629a377f05296c9319be26241754f2e31d237012aa6a41c36c4d607beaccd902bf62c23a27b43521a11597eb09', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hashkey',
            field=models.TextField(default='b550bc40a5c9bcd84ce67683eae8f95da783a765', unique=True),
        ),
    ]
