# Generated by Django 4.0.1 on 2022-02-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_message_hashkey_alter_metauser_hashkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='hashkey',
            field=models.TextField(default='0151eda9232958dec3a37110f088a000e52b721cc2fe18f5074aab468e0a7bb9', unique=True),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='hashkey',
            field=models.TextField(default='2736e6769e36c13c924aa51245f33b3a2a1ca60ee855b7b68d9f4b97478d70de5c9371488fd66a8ab8fd1cf3d34fae64ddebb626e9c894ae6437788369e80ff3', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hashkey',
            field=models.TextField(default='7d575aa12941b5bc02005dbef77745716bb9a3ac', unique=True),
        ),
    ]
