# Generated by Django 4.0.1 on 2022-06-16 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_stripeaccountinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='stripeAccountTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.CharField(max_length=500)),
                ('payoutAmount', models.FloatField(default=0.0)),
                ('payputOrderInfo', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('stripeAccountInfoID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.stripeaccountinfo')),
            ],
        ),
    ]
