# Generated by Django 4.0.5 on 2022-07-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_orderledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderledger',
            name='orderDetailID',
        ),
    ]
