# Generated by Django 4.0.5 on 2022-07-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_orderledger_orderdetailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productVariants',
            field=models.TextField(default='Large'),
        ),
    ]
