# Generated by Django 4.0.5 on 2022-10-13 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_product_shopid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blascore',
            name='levelID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.level'),
        ),
        migrations.AlterField(
            model_name='blascore',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='bodegasocial',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='bodegasupport',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='cashflowledger',
            name='bodegaCustomerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.customerpayment'),
        ),
        migrations.AlterField(
            model_name='cashflowledger',
            name='stripeAccountInfoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.stripeaccountinfo'),
        ),
        migrations.AlterField(
            model_name='collectionpage',
            name='collectionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.productcollection'),
        ),
        migrations.AlterField(
            model_name='creatorsubscription',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='creatorsubscription',
            name='shopID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.shop'),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='level',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='metauseraccountstatus',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='metausersocial',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='metausertags',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='munchiesvideo',
            name='munchiesPageID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.munchiespage'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='payment_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userpayment'),
        ),
        migrations.AlterField(
            model_name='orderfailure',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='orderfailure',
            name='order_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.orderdetail'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.orderdetail'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product'),
        ),
        migrations.AlterField(
            model_name='orderledger',
            name='customerMetauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='orderledger',
            name='merchantStripeAccountInfoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.stripeaccountinfo'),
        ),
        migrations.AlterField(
            model_name='orderledger',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product'),
        ),
        migrations.AlterField(
            model_name='orderledger',
            name='userAddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.useraddress'),
        ),
        migrations.AlterField(
            model_name='ordersuccess',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='ordersuccess',
            name='order_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.orderdetail'),
        ),
        migrations.AlterField(
            model_name='product',
            name='collectionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.productcollection'),
        ),
        migrations.AlterField(
            model_name='productcollection',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='productmetadata',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='country',
            field=models.TextField(max_length=6),
        ),
        migrations.AlterField(
            model_name='stripeaccountinfo',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='stripeaccounttransfer',
            name='stripeAccountInfoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.stripeaccountinfo'),
        ),
        migrations.AlterField(
            model_name='stripecharges',
            name='bodegaCustomerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.customerpayment'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='shopID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.shop'),
        ),
        migrations.AlterField(
            model_name='sysopsagent',
            name='departmentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.bodegadept'),
        ),
        migrations.AlterField(
            model_name='sysopsagent',
            name='levelID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.level'),
        ),
        migrations.AlterField(
            model_name='sysopsagent',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='sysopsagentrepo',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='sysopsagentrepo',
            name='sysops_agentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.sysopsagent'),
        ),
        migrations.AlterField(
            model_name='sysopsdemandnode',
            name='bla_ScoreID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.blascore'),
        ),
        migrations.AlterField(
            model_name='sysopsdemandnode',
            name='demand_metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='sysopsproject',
            name='divisionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.bodegadept'),
        ),
        migrations.AlterField(
            model_name='sysopsproject',
            name='levelID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.level'),
        ),
        migrations.AlterField(
            model_name='sysopsproject',
            name='owner_agentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.sysopsagent'),
        ),
        migrations.AlterField(
            model_name='sysopsproject',
            name='owner_metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='sysopssupplynode',
            name='bla_ScoreID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.blascore'),
        ),
        migrations.AlterField(
            model_name='sysopssupplynode',
            name='supply_metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='sysopssupplynode',
            name='supply_shopID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.shop'),
        ),
        migrations.AlterField(
            model_name='websitesitemapconfig',
            name='ownerMetaUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='yerrrcollaboration',
            name='collaboratorMetaUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='yerrrcollaboration',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product'),
        ),
    ]
