# Generated by Django 4.0.1 on 2022-02-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_message_hashkey_alter_metauser_hashkey_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_sizeID',
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='message',
            name='hashkey',
            field=models.TextField(default='8b5e1c12979b0f59217588400c8f3323d6a5b0427bc24f74499da3787d5aeb03', unique=True),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='hashkey',
            field=models.TextField(default='5465a4b47a5e37b281369db072a70f9cc6e7e2d64e57a352e6716735880f84eccf29b3202ea7f19973a69be7b6abdca2a3bce17c2d242d78d35b91410d198424', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hashkey',
            field=models.TextField(default='1d29b22295e1cd118f5c59cd79766f503500368a', unique=True),
        ),
        migrations.DeleteModel(
            name='Product_Variants',
        ),
    ]
