# Generated by Django 4.0.1 on 2022-06-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_stripeaccounttransfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripeaccounttransfer',
            old_name='payputOrderInfo',
            new_name='payoutOrderInfo',
        ),
    ]
