# Generated by Django 4.0.1 on 2022-06-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_rename_payputorderinfo_stripeaccounttransfer_payoutorderinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='stripeAccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0)),
                ('currency', models.TextField()),
                ('pendingAmount', models.FloatField(default=0.0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
