# Generated by Django 4.0.1 on 2022-02-08 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_product_price_sizeid_product_discounted_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='disocunt_percent',
            new_name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='collaborationID',
        ),
        migrations.AddField(
            model_name='collaboration',
            name='product_ID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='hashkey',
            field=models.TextField(default='6342852271ba59833c5e74cc4814601631d1d863bed20a1eb18bdf5abf247e77', unique=True),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='hashkey',
            field=models.TextField(default='92f154a8b44f0fa613ee5b6bcb50dc4c889e68c3cbb25baf48fc39622c3a0338f15ceaf35a39d71c28610046f2f3f2f2b29e6e2aeff4d3c6f5a77d8c1e3caccb', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hashkey',
            field=models.TextField(default='61c5405869a151759bd89933a08066189fa4445f', unique=True),
        ),
    ]
