# Generated by Django 4.0.5 on 2022-07-12 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_product_productvariants'),
    ]

    operations = [
        migrations.CreateModel(
            name='bodegaSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(default='ORDER STATUS', max_length=255)),
                ('message', models.CharField(default='PROBLEM STATEMENT', max_length=500)),
                ('ticketActive', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('metauserID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.metauser')),
            ],
        ),
    ]
