# Generated by Django 4.0.1 on 2022-06-16 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_stripeaccountbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='stripeCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeChargeID', models.CharField(max_length=300)),
                ('amount', models.FloatField(default=0.0)),
                ('currency', models.TextField(default='us')),
                ('description', models.CharField(max_length=400)),
                ('capturedStatus', models.BooleanField(default=False)),
                ('riskScore', models.IntegerField(default=0)),
                ('last4', models.IntegerField(default=0)),
                ('paymentStatus', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('stripeAccountInfoID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.stripeaccountinfo')),
            ],
        ),
    ]
