# Generated by Django 4.0.1 on 2022-02-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_rename_disocunt_percent_discount_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='hashkey',
            field=models.TextField(default='fe3a290c94bb606f2639046cb872cc1d3c9d492ac23e44393b385e0a82c89700', unique=True),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='hashkey',
            field=models.TextField(default='ca681d40d387962875c12f53b74a609a51492ae8a82b38215ab3cca34d153b4334cacd9fae6e479813cc49e776537182f1fe6198e12f48b191be37591540a70a', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hashkey',
            field=models.TextField(default='dc7c9d0e9da12707dc8c787e7d07492ec7a420e2', unique=True),
        ),
    ]
