# Generated by Django 4.0.5 on 2022-07-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_bodegasupport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_categoryID',
            new_name='productCategoryID',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_name',
            field=models.TextField(choices=[('SHIRTS', 'SHIRTS'), ('BOTTOMS', 'BOTTOMS'), ('SNEAKERS', 'SNEAKERS'), ('THERMALS', 'THERMALS'), ('SHORTS', 'SHORTS'), ('HOME-DECOR', 'HOME-DECOR'), ('DIGITAL-ART', 'DIGITAL-ART'), ('MUSIC-FILE', 'MUSIC-FILE'), ('COLLECTIBLES', 'COLLECTIBLES'), ('DIGITAL-COLLECTIBLES', 'DIGITAL-COLLECTIBLES'), ('PHYSICAL-ACCESSORIES', 'PHYSICAL-ACCESSORIES'), ('ENTERTAINMENT', 'ENTERTAINMENT'), ('EDUCATIONAL', 'EDUCATIONAL')]),
        ),
    ]
