# Generated by Django 4.0.1 on 2022-06-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_stripecharges'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecharges',
            name='stripeCustomerID',
            field=models.CharField(default=None, max_length=400),
            preserve_default=False,
        ),
    ]
