# Generated by Django 4.0.1 on 2022-02-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_message_hashkey_alter_metauser_hashkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='hashkey',
            field=models.TextField(default='e86b54b65e71cd12d0254158cb726fc314248c9bd348f91b3252f0f0ed5b4f99', unique=True),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='hashkey',
            field=models.TextField(default='44ad87338f0be112cf2ebfa9af8b1b031b7d2748bcdab019e4245f7f826264b18f6d794322a970ad27dc055bc686196062b1d8249becdecdd8c967739dd927e7', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hashkey',
            field=models.TextField(default='0124f90c94580a124da15d24915f4ac6e82e62ad', unique=True),
        ),
    ]
