# Generated by Django 4.0.1 on 2022-02-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_message_hashkey_alter_metauser_hashkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='hashkey',
            field=models.TextField(default='4aae6aa0475e19482c3f2b66544bbfcff613b8f04cae37a45b035324441e3d1a', unique=True),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='hashkey',
            field=models.TextField(default='1bcd98cfb5b6ce82c19251c3c326056ac78cafdb9e15e67858d4fa3f3aba68e404aacb6c768368c0e872bed46e62452b9a103e369a93cd5ca7150976ea30a844', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hashkey',
            field=models.TextField(default='347b4a86ec03e8ee9957ff7619f0a10c7f4c855b', unique=True),
        ),
    ]
