# Generated by Django 4.0.1 on 2022-06-21 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_stripecharges_stripecustomerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='creatorSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriptionName', models.CharField(max_length=300)),
                ('subscriptionDescription', models.CharField(max_length=500)),
                ('amount', models.IntegerField(default=0)),
                ('currency', models.CharField(max_length=255)),
                ('chargingFrequency', models.CharField(max_length=300)),
                ('stripeProductID', models.CharField(max_length=400)),
                ('stripeCustomerID', models.CharField(max_length=400)),
                ('stripePriceID', models.CharField(max_length=400)),
                ('stripeSubscriptionID', models.CharField(max_length=400)),
                ('metauserID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.metauser')),
            ],
        ),
    ]
