# Generated by Django 4.0.1 on 2022-02-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_message_hashkey_alter_metauser_hashkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='hashkey',
            field=models.TextField(default='a41807a3f6b1412a8065b25f593b6b505ddb9ce69524c59cc64ec791a9a2dfcb', unique=True),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='hashkey',
            field=models.TextField(default='ea0d38b1e7638684fb227e3ec8683b1608ba79badedf1dfa1760aec34b9c825bdc74f8b0de68118ccd3b57bea74808eceeea32c9419f3575ce0cf9087f64db7b', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hashkey',
            field=models.TextField(default='bafee22664858af1a9e3280d30c2762209970188', unique=True),
        ),
    ]
