# Generated by Django 4.0.1 on 2022-02-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_message_hashkey_alter_metauser_hashkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='hashkey',
            field=models.TextField(default='935ecca20f861b9afee3e874039443084720303bd7a0d6885a0ec60b181d2ef1', unique=True),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='hashkey',
            field=models.TextField(default='b7aa17fc1bba9fbcadcc4d324749a6b8f269515a6faa17f3de1568bd208c5e58e60c10a476d9b4d1425fe494a26d1d24d2e90f9ecbb756562cad5ad81c4f6b71', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hashkey',
            field=models.TextField(default='5160bc39684d33507b0a5e5abec7bcb5a35e24dc', unique=True),
        ),
    ]
