# Generated by Django 4.0.5 on 2022-08-03 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_remove_footerbar_metauserid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaUserAccountStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPaidSubscriber', models.BooleanField(default=False)),
                ('isAccountLocked', models.BooleanField(default=False)),
                ('referralCode', models.TextField(unique=True)),
                ('activatePaywall', models.BooleanField(default=False)),
                ('metauserID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.metauser')),
            ],
        ),
    ]
