# Generated by Django 4.0.1 on 2022-02-08 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_message_hashkey_alter_metauser_hashkey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Your campaign definition')),
                ('desc', models.TextField(default='Describe your campaign')),
                ('type', models.TextField(choices=[('FIXED-PAYMENT', 'FIXED-PAYMENT'), ('BARTER-DEAL', 'BARTER-DEAL'), ('COMMISSION-%-ON-SALES', 'COMMISSION-%-ON-SALES'), ('FREE-HELP-FROM-THE-COMMUNITY', 'FREE-HELP-FROM-THE-COMMUNITY')])),
                ('collab_status', models.BooleanField(default=False)),
                ('creator_pitch', models.TextField()),
                ('bid_type', models.TextField(choices=[('FIXED-PAYMENT', 'FIXED-PAYMENT'), ('BARTER-DEAL', 'BARTER-DEAL'), ('COMMISSION-%-ON-SALES', 'COMMISSION-%-ON-SALES'), ('FREE-HELP-FROM-THE-COMMUNITY', 'FREE-HELP-FROM-THE-COMMUNITY')])),
                ('bid_amount', models.FloatField(default=0.0)),
                ('accept_bid', models.BooleanField(default=False)),
                ('created_at', models.DateField()),
                ('modified_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='hashkey',
            field=models.TextField(default='b522e82b0413b02722d4ac395b4cbfba7471b7737f060756a5bbc000446405ee', unique=True),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='hashkey',
            field=models.TextField(default='0a73e5a878c8f898b475b2fd17adc2e814d8baed13a17a6f61d658873535ca13b48058700b34c16415b37ae7086807a7e13a4b167705ebea8659646acf4f8f1b', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hashkey',
            field=models.TextField(default='2bbf814d4fbbfdb43ce13ad2ed7346eb1fa0fdf1', unique=True),
        ),
        migrations.DeleteModel(
            name='Collaboration',
        ),
        migrations.AddField(
            model_name='collab',
            name='product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product'),
        ),
        migrations.AddField(
            model_name='collab',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.metauser'),
        ),
    ]
