# Generated by Django 4.0.5 on 2022-08-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_metauseraccountstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='type_of_room',
            field=models.TextField(default='Empty'),
        ),
    ]
