# Generated by Django 4.0.5 on 2022-08-12 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_chatroom_type_of_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='category_desc',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='category_image1',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='category_image2',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='category_image3',
        ),
    ]
