# Generated by Django 4.0.1 on 2022-02-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_collab_alter_message_hashkey_alter_metauser_hashkey_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collab',
            new_name='Collaboration',
        ),
        migrations.AlterField(
            model_name='message',
            name='hashkey',
            field=models.TextField(default='4bf344dbafa9a2ae2b5df1ded13e993f077781f62bf9d42b1924e6f2802fbe6e', unique=True),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='hashkey',
            field=models.TextField(default='a6088f455e74e1f2ec2db8d3cd26b8f8cfd6f918f983faf29c7928920ea229cacca735f14bf95e0085534458e7f6e1be44ac4c9319a79137c1d5eee1135f6f4d', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hashkey',
            field=models.TextField(default='3818b07316019250b83e0f34927bb2a72431e0e3', unique=True),
        ),
    ]
