# Generated by Django 4.0.1 on 2022-02-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_rename_collab_collaboration_alter_message_hashkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='hashkey',
            field=models.TextField(default='d700e300ed0f52d048e8363e0485b4e9525f66384b11c5bc9079e86aaca10eed', unique=True),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='hashkey',
            field=models.TextField(default='15a4e2a03ef7a304f8d241b09073558196e7624122bd7cf7d6928276984c26c4da6188378321b9b017473845c4b3b34e4d9c17bde742969a52da2d89333a1263', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hashkey',
            field=models.TextField(default='506f1f6b67b15b7ff74e21371c188ffc8c91e16b', unique=True),
        ),
    ]
