# Generated by Django 4.0.1 on 2022-06-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image1',
            field=models.FileField(default='https://bdgdaostorage.blob.core.windows.net/media/product/product_image1/white-transparent-bdga.png', upload_to='product/product_image1'),
        ),
    ]
