# Generated by Django 4.0.5 on 2022-08-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_contentpage_ownermetauserid'),
    ]

    operations = [
        migrations.AddField(
            model_name='metauseraccountstatus',
            name='notificationMessage',
            field=models.TextField(default='Welcome to Project-Bodega'),
        ),
        migrations.AddField(
            model_name='metauseraccountstatus',
            name='notificationStatus',
            field=models.BooleanField(default=False),
        ),
    ]
