# Generated by Django 4.0.1 on 2022-06-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_product_product_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecharges',
            name='stripePaymentMethodID',
            field=models.CharField(blank=True, default='None', max_length=400),
        ),
    ]
