# Generated by Django 4.0.1 on 2022-02-08 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_message_hashkey_alter_metauser_hashkey_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaboration',
            old_name='type',
            new_name='creator_collab_choice',
        ),
        migrations.RemoveField(
            model_name='collaboration',
            name='collab_status',
        ),
        migrations.AddField(
            model_name='collaboration',
            name='shop_ID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.shop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product'),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='session_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.shopping_session'),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='message',
            name='hashkey',
            field=models.TextField(default='77ecd5b1a3979584fd8ebd9f648b827379e49ac52b524abc348cabffcfbe6d2a', unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='hashkey',
            field=models.TextField(default='8888bc800c288e0e9441ffd687453dd895390f494b71f0f90b69fb8dbf6bf5dc1ace423fc096cd1a7f1e4d8e6da831c39b463dc2c2f2a577a33ffb6b9be1d5ce', unique=True),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='payment_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user_payment'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product'),
        ),
        migrations.AlterField(
            model_name='particpants',
            name='chat_room_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.chat_room'),
        ),
        migrations.AlterField(
            model_name='particpants',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hashkey',
            field=models.TextField(default='31e7c2770ddafaf219c7718d6705904a1ed99779', unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='shopping_session',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
        migrations.AlterField(
            model_name='social',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.metauser'),
        ),
    ]
