# Generated by Django 4.0.5 on 2022-08-16 14:42

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_metauseraccountstatus_notificationmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headingText', models.TextField(blank=True)),
                ('subheadingText', models.TextField(blank=True)),
                ('paragraphText', models.TextField(blank=True)),
                ('media1', models.FileField(default='8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='bodegaMerchant/webshop/newsletters/media1')),
                ('media2', models.FileField(default='8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='bodegaMerchant/webshop/newsletters/media2')),
                ('media3', models.FileField(default='8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='bodegaMerchant/webshop/newsletters/media3')),
                ('media4', models.FileField(default='8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='bodegaMerchant/webshop/newsletters/media4')),
                ('buttonText1', models.CharField(default='null', max_length=255)),
                ('buttonText2', models.CharField(default='null', max_length=255)),
                ('buttonText3', models.CharField(default='null', max_length=255)),
                ('buttonText4', models.CharField(default='null', max_length=255)),
                ('collectionButtonID1', models.IntegerField(default=0)),
                ('collectionButtonID2', models.IntegerField(default=0)),
                ('collectionButtonID3', models.IntegerField(default=0)),
                ('collectionButtonID4', models.IntegerField(default=0)),
                ('backgroundImage', models.FileField(default='8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='bodegaMerchant/webshop/newsletters/backgroundImage')),
                ('backgroundColor', models.TextField(default='TRANSPARENT')),
                ('NewsletterCoverImage', models.FileField(default='8954256a-cc48-4d73-a863-5c8ebe3c426c.jpeg', upload_to='bodegaMerchant/webshop/newsletter/NewsletterCoverImage')),
                ('isPrivate', models.BooleanField(default=False)),
                ('isSubscriptionPage', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('ownerMetaUserID', models.ForeignKey(default=backend.models.get_sentinel_MetaUser_id, on_delete=models.SET(backend.models.get_sentinel_MetaUser), to='backend.metauser')),
            ],
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='room_hashkey',
        ),
        migrations.RemoveField(
            model_name='message',
            name='hashkey',
        ),
        migrations.RemoveField(
            model_name='message',
            name='upload_file',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='ownerMetaUserID',
            field=models.ForeignKey(default=backend.models.get_sentinel_MetaUser_id, on_delete=models.SET(backend.models.get_sentinel_MetaUser), to='backend.metauser'),
        ),
        migrations.AddField(
            model_name='collection',
            name='metauserID',
            field=models.ForeignKey(default=backend.models.get_sentinel_MetaUser_id, on_delete=models.SET(backend.models.get_sentinel_MetaUser), to='backend.metauser'),
        ),
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='NewsletterSubscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('metauserID', models.ForeignKey(default=backend.models.get_sentinel_MetaUser_id, on_delete=models.SET(backend.models.get_sentinel_MetaUser), to='backend.metauser')),
                ('newsletterID', models.ForeignKey(default=backend.models.get_sentinel_Newsletter_id, on_delete=models.SET(backend.models.get_sentinel_Newsletter), to='backend.newsletter')),
            ],
        ),
    ]
