# Generated by Django 4.0.1 on 2022-02-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_rename_type_collaboration_creator_collab_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='hashkey',
            field=models.TextField(default='06d9c9de191a1a9dc6a871c1537b75193e0ee8d4567d22f463c29729d841fae6', unique=True),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='hashkey',
            field=models.TextField(default='c0d71cf7b307c33e02705ec792fc08e866dd1837b7ee64f5f7dd892b30681a43a7c7c346cc986a6519d0e2f47823c828ae1338a90ff249ca3668a64cc6eb8c57', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hashkey',
            field=models.TextField(default='00fef5a476579db48ec1b71f6a34923e2676308c', unique=True),
        ),
    ]
