# Generated by Django 4.0.5 on 2022-08-16 15:17

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_newsletter_remove_chatroom_room_hashkey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodegaServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('desc', models.TextField(default='Why was this room created?')),
                ('tags', models.TextField(default='#ROOM')),
                ('isRoomPrivate', models.BooleanField(default=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('ownerMetaUserID', models.ForeignKey(default=backend.models.get_sentinel_MetaUser_id, on_delete=models.SET(backend.models.get_sentinel_MetaUser), to='backend.metauser')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='chat_room_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.bodegaserver'),
        ),
    ]
