# Generated by Django 4.0.1 on 2022-06-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_stripecustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripecharges',
            name='last4',
        ),
        migrations.RemoveField(
            model_name='stripecharges',
            name='riskScore',
        ),
        migrations.RemoveField(
            model_name='stripecharges',
            name='stripeAccountInfoID',
        ),
    ]
