# Generated by Django 4.0.5 on 2022-08-16 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_bodegaserver_alter_message_chat_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='metauserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.metauser'),
        ),
    ]
