# Generated by Django 4.0.1 on 2022-06-29 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_remove_stripecharges_last4_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stripeCustomer',
            new_name='bodegaCustomer',
        ),
        migrations.AddField(
            model_name='stripecharges',
            name='bodegaCustomerID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='backend.bodegacustomer'),
            preserve_default=False,
        ),
    ]
