# Generated by Django 4.0.1 on 2022-06-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_rename_stripecustomer_bodegacustomer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='is_room_active',
            new_name='isRoomPrivate',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='rules',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='tags',
            field=models.TextField(default='#ROOM'),
        ),
    ]
